server:
  port: 8080

spring:
  application:
    name: cloud-demo-controller

eureka:
  client:
    service-url:
      defaultZone: http://root:7778888@192.168.1.114:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true